$(document).ready(function(){
    $("#app").click(function(){
      $("d").hide();
      $("e").hide();
      $("f").hide();
      $("h").hide();
      $("j").hide();
      $("k").hide();
      $("m").hide();
      $("n").hide();
      $("o").hide();
    });
    $("#all").click(function(){
      $("c").show();
      $("g").show();
      $("l").show();
    });
  });
  $(document).ready(function(){
    $("#all").click(function(){
      $("c").show();
      $("d").show();
      $("e").show();
      $("f").show();
      $("g").show();
      $("h").show();
      $("j").show();
      $("k").show();
      $("l").show();
      $("m").show();
      $("n").show();
      $("o").show();
    });
    $("#all").click(function(){
      $("c").show();
      $("g").show();
      $("l").show();
    });
  });
  $(document).ready(function(){
    $("#product").click(function(){
      $("c").hide();
      $("e").hide();
      $("f").hide();
      $("j").hide();
      $("k").hide();
      $("l").hide();
      $("g").hide();
      $("n").hide();
      $("o").hide();
    });
    $("#product").click(function(){
      $("d").show();
      $("h").show();
      $("m").show();
    });
  });
    $(document).ready(function(){
    $("#branding").click(function(){
      $("c").hide();
      $("d").hide();
      $("f").hide();
      $("g").hide();
      $("h").hide();
      $("k").hide();
      $("l").hide();
      $("m").hide();
      $("o").hide();
    });
    $("#branding").click(function(){
      $("e").show();
      $("j").show();
      $("n").show();
    });
  });
    $(document).ready(function(){
    $("#books").click(function(){
      $("c").hide();
      $("d").hide();
      $("e").hide();
      $("g").hide();
      $("h").hide();
      $("j").hide();
      $("l").hide();
      $("m").hide();
      $("n").hide();
    });
    $("#books").click(function(){
      $("f").show();
      $("k").show();
      $("o").show();
    });
  });